ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "role" TYPE TEXT USING lower("role"::text);
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'agent';

DROP TYPE IF EXISTS "UserRole";
